[package]
name = "student-management-system-backend"
version = "0.1.0"
authors = ["sundoge"]
edition = "2018"

[dependencies]
actix = "0.7.9"
actix-web = "0.7.18"
diesel = { version = "1.4.2", features = ["mysql", "r2d2"] }
dotenv = "0.13.0"
r2d2 = "0.8.3"
env_logger = "0.6.1"